# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/SnakeMOGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/SnakeMOGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/SnakeMOGame/CMakeFiles /home/ubuntu/SnakeMOGame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/SnakeMOGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Snake

# Build rule for target.
Snake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Snake
.PHONY : Snake

# fast build rule for target.
Snake/fast:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/build
.PHONY : Snake/fast

#=============================================================================
# Target rules for targets named SnakeServer

# Build rule for target.
SnakeServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SnakeServer
.PHONY : SnakeServer

# fast build rule for target.
SnakeServer/fast:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/build
.PHONY : SnakeServer/fast

#=============================================================================
# Target rules for targets named SnakeClient

# Build rule for target.
SnakeClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SnakeClient
.PHONY : SnakeClient

# fast build rule for target.
SnakeClient/fast:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/build
.PHONY : SnakeClient/fast

Snake/Console.o: Snake/Console.cpp.o

.PHONY : Snake/Console.o

# target to build an object file
Snake/Console.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Console.cpp.o
.PHONY : Snake/Console.cpp.o

Snake/Console.i: Snake/Console.cpp.i

.PHONY : Snake/Console.i

# target to preprocess a source file
Snake/Console.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Console.cpp.i
.PHONY : Snake/Console.cpp.i

Snake/Console.s: Snake/Console.cpp.s

.PHONY : Snake/Console.s

# target to generate assembly for a file
Snake/Console.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Console.cpp.s
.PHONY : Snake/Console.cpp.s

Snake/ConsoleBuffer.o: Snake/ConsoleBuffer.cpp.o

.PHONY : Snake/ConsoleBuffer.o

# target to build an object file
Snake/ConsoleBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ConsoleBuffer.cpp.o
.PHONY : Snake/ConsoleBuffer.cpp.o

Snake/ConsoleBuffer.i: Snake/ConsoleBuffer.cpp.i

.PHONY : Snake/ConsoleBuffer.i

# target to preprocess a source file
Snake/ConsoleBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ConsoleBuffer.cpp.i
.PHONY : Snake/ConsoleBuffer.cpp.i

Snake/ConsoleBuffer.s: Snake/ConsoleBuffer.cpp.s

.PHONY : Snake/ConsoleBuffer.s

# target to generate assembly for a file
Snake/ConsoleBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ConsoleBuffer.cpp.s
.PHONY : Snake/ConsoleBuffer.cpp.s

Snake/Context.o: Snake/Context.cpp.o

.PHONY : Snake/Context.o

# target to build an object file
Snake/Context.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Context.cpp.o
.PHONY : Snake/Context.cpp.o

Snake/Context.i: Snake/Context.cpp.i

.PHONY : Snake/Context.i

# target to preprocess a source file
Snake/Context.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Context.cpp.i
.PHONY : Snake/Context.cpp.i

Snake/Context.s: Snake/Context.cpp.s

.PHONY : Snake/Context.s

# target to generate assembly for a file
Snake/Context.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Context.cpp.s
.PHONY : Snake/Context.cpp.s

Snake/Food.o: Snake/Food.cpp.o

.PHONY : Snake/Food.o

# target to build an object file
Snake/Food.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Food.cpp.o
.PHONY : Snake/Food.cpp.o

Snake/Food.i: Snake/Food.cpp.i

.PHONY : Snake/Food.i

# target to preprocess a source file
Snake/Food.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Food.cpp.i
.PHONY : Snake/Food.cpp.i

Snake/Food.s: Snake/Food.cpp.s

.PHONY : Snake/Food.s

# target to generate assembly for a file
Snake/Food.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Food.cpp.s
.PHONY : Snake/Food.cpp.s

Snake/GameObject.o: Snake/GameObject.cpp.o

.PHONY : Snake/GameObject.o

# target to build an object file
Snake/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/GameObject.cpp.o
.PHONY : Snake/GameObject.cpp.o

Snake/GameObject.i: Snake/GameObject.cpp.i

.PHONY : Snake/GameObject.i

# target to preprocess a source file
Snake/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/GameObject.cpp.i
.PHONY : Snake/GameObject.cpp.i

Snake/GameObject.s: Snake/GameObject.cpp.s

.PHONY : Snake/GameObject.s

# target to generate assembly for a file
Snake/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/GameObject.cpp.s
.PHONY : Snake/GameObject.cpp.s

Snake/GameObjectRegistry.o: Snake/GameObjectRegistry.cpp.o

.PHONY : Snake/GameObjectRegistry.o

# target to build an object file
Snake/GameObjectRegistry.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/GameObjectRegistry.cpp.o
.PHONY : Snake/GameObjectRegistry.cpp.o

Snake/GameObjectRegistry.i: Snake/GameObjectRegistry.cpp.i

.PHONY : Snake/GameObjectRegistry.i

# target to preprocess a source file
Snake/GameObjectRegistry.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/GameObjectRegistry.cpp.i
.PHONY : Snake/GameObjectRegistry.cpp.i

Snake/GameObjectRegistry.s: Snake/GameObjectRegistry.cpp.s

.PHONY : Snake/GameObjectRegistry.s

# target to generate assembly for a file
Snake/GameObjectRegistry.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/GameObjectRegistry.cpp.s
.PHONY : Snake/GameObjectRegistry.cpp.s

Snake/InputState.o: Snake/InputState.cpp.o

.PHONY : Snake/InputState.o

# target to build an object file
Snake/InputState.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/InputState.cpp.o
.PHONY : Snake/InputState.cpp.o

Snake/InputState.i: Snake/InputState.cpp.i

.PHONY : Snake/InputState.i

# target to preprocess a source file
Snake/InputState.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/InputState.cpp.i
.PHONY : Snake/InputState.cpp.i

Snake/InputState.s: Snake/InputState.cpp.s

.PHONY : Snake/InputState.s

# target to generate assembly for a file
Snake/InputState.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/InputState.cpp.s
.PHONY : Snake/InputState.cpp.s

Snake/MemoryBitStream.o: Snake/MemoryBitStream.cpp.o

.PHONY : Snake/MemoryBitStream.o

# target to build an object file
Snake/MemoryBitStream.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/MemoryBitStream.cpp.o
.PHONY : Snake/MemoryBitStream.cpp.o

Snake/MemoryBitStream.i: Snake/MemoryBitStream.cpp.i

.PHONY : Snake/MemoryBitStream.i

# target to preprocess a source file
Snake/MemoryBitStream.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/MemoryBitStream.cpp.i
.PHONY : Snake/MemoryBitStream.cpp.i

Snake/MemoryBitStream.s: Snake/MemoryBitStream.cpp.s

.PHONY : Snake/MemoryBitStream.s

# target to generate assembly for a file
Snake/MemoryBitStream.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/MemoryBitStream.cpp.s
.PHONY : Snake/MemoryBitStream.cpp.s

Snake/Move.o: Snake/Move.cpp.o

.PHONY : Snake/Move.o

# target to build an object file
Snake/Move.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Move.cpp.o
.PHONY : Snake/Move.cpp.o

Snake/Move.i: Snake/Move.cpp.i

.PHONY : Snake/Move.i

# target to preprocess a source file
Snake/Move.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Move.cpp.i
.PHONY : Snake/Move.cpp.i

Snake/Move.s: Snake/Move.cpp.s

.PHONY : Snake/Move.s

# target to generate assembly for a file
Snake/Move.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Move.cpp.s
.PHONY : Snake/Move.cpp.s

Snake/MoveList.o: Snake/MoveList.cpp.o

.PHONY : Snake/MoveList.o

# target to build an object file
Snake/MoveList.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/MoveList.cpp.o
.PHONY : Snake/MoveList.cpp.o

Snake/MoveList.i: Snake/MoveList.cpp.i

.PHONY : Snake/MoveList.i

# target to preprocess a source file
Snake/MoveList.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/MoveList.cpp.i
.PHONY : Snake/MoveList.cpp.i

Snake/MoveList.s: Snake/MoveList.cpp.s

.PHONY : Snake/MoveList.s

# target to generate assembly for a file
Snake/MoveList.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/MoveList.cpp.s
.PHONY : Snake/MoveList.cpp.s

Snake/NetworkManager.o: Snake/NetworkManager.cpp.o

.PHONY : Snake/NetworkManager.o

# target to build an object file
Snake/NetworkManager.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/NetworkManager.cpp.o
.PHONY : Snake/NetworkManager.cpp.o

Snake/NetworkManager.i: Snake/NetworkManager.cpp.i

.PHONY : Snake/NetworkManager.i

# target to preprocess a source file
Snake/NetworkManager.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/NetworkManager.cpp.i
.PHONY : Snake/NetworkManager.cpp.i

Snake/NetworkManager.s: Snake/NetworkManager.cpp.s

.PHONY : Snake/NetworkManager.s

# target to generate assembly for a file
Snake/NetworkManager.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/NetworkManager.cpp.s
.PHONY : Snake/NetworkManager.cpp.s

Snake/ObjectManager.o: Snake/ObjectManager.cpp.o

.PHONY : Snake/ObjectManager.o

# target to build an object file
Snake/ObjectManager.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ObjectManager.cpp.o
.PHONY : Snake/ObjectManager.cpp.o

Snake/ObjectManager.i: Snake/ObjectManager.cpp.i

.PHONY : Snake/ObjectManager.i

# target to preprocess a source file
Snake/ObjectManager.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ObjectManager.cpp.i
.PHONY : Snake/ObjectManager.cpp.i

Snake/ObjectManager.s: Snake/ObjectManager.cpp.s

.PHONY : Snake/ObjectManager.s

# target to generate assembly for a file
Snake/ObjectManager.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ObjectManager.cpp.s
.PHONY : Snake/ObjectManager.cpp.s

Snake/ScoreBoardManager.o: Snake/ScoreBoardManager.cpp.o

.PHONY : Snake/ScoreBoardManager.o

# target to build an object file
Snake/ScoreBoardManager.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ScoreBoardManager.cpp.o
.PHONY : Snake/ScoreBoardManager.cpp.o

Snake/ScoreBoardManager.i: Snake/ScoreBoardManager.cpp.i

.PHONY : Snake/ScoreBoardManager.i

# target to preprocess a source file
Snake/ScoreBoardManager.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ScoreBoardManager.cpp.i
.PHONY : Snake/ScoreBoardManager.cpp.i

Snake/ScoreBoardManager.s: Snake/ScoreBoardManager.cpp.s

.PHONY : Snake/ScoreBoardManager.s

# target to generate assembly for a file
Snake/ScoreBoardManager.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/ScoreBoardManager.cpp.s
.PHONY : Snake/ScoreBoardManager.cpp.s

Snake/Snake.o: Snake/Snake.cpp.o

.PHONY : Snake/Snake.o

# target to build an object file
Snake/Snake.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Snake.cpp.o
.PHONY : Snake/Snake.cpp.o

Snake/Snake.i: Snake/Snake.cpp.i

.PHONY : Snake/Snake.i

# target to preprocess a source file
Snake/Snake.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Snake.cpp.i
.PHONY : Snake/Snake.cpp.i

Snake/Snake.s: Snake/Snake.cpp.s

.PHONY : Snake/Snake.s

# target to generate assembly for a file
Snake/Snake.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Snake.cpp.s
.PHONY : Snake/Snake.cpp.s

Snake/SocketAddress.o: Snake/SocketAddress.cpp.o

.PHONY : Snake/SocketAddress.o

# target to build an object file
Snake/SocketAddress.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketAddress.cpp.o
.PHONY : Snake/SocketAddress.cpp.o

Snake/SocketAddress.i: Snake/SocketAddress.cpp.i

.PHONY : Snake/SocketAddress.i

# target to preprocess a source file
Snake/SocketAddress.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketAddress.cpp.i
.PHONY : Snake/SocketAddress.cpp.i

Snake/SocketAddress.s: Snake/SocketAddress.cpp.s

.PHONY : Snake/SocketAddress.s

# target to generate assembly for a file
Snake/SocketAddress.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketAddress.cpp.s
.PHONY : Snake/SocketAddress.cpp.s

Snake/SocketAddressFactory.o: Snake/SocketAddressFactory.cpp.o

.PHONY : Snake/SocketAddressFactory.o

# target to build an object file
Snake/SocketAddressFactory.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketAddressFactory.cpp.o
.PHONY : Snake/SocketAddressFactory.cpp.o

Snake/SocketAddressFactory.i: Snake/SocketAddressFactory.cpp.i

.PHONY : Snake/SocketAddressFactory.i

# target to preprocess a source file
Snake/SocketAddressFactory.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketAddressFactory.cpp.i
.PHONY : Snake/SocketAddressFactory.cpp.i

Snake/SocketAddressFactory.s: Snake/SocketAddressFactory.cpp.s

.PHONY : Snake/SocketAddressFactory.s

# target to generate assembly for a file
Snake/SocketAddressFactory.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketAddressFactory.cpp.s
.PHONY : Snake/SocketAddressFactory.cpp.s

Snake/SocketUtil.o: Snake/SocketUtil.cpp.o

.PHONY : Snake/SocketUtil.o

# target to build an object file
Snake/SocketUtil.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketUtil.cpp.o
.PHONY : Snake/SocketUtil.cpp.o

Snake/SocketUtil.i: Snake/SocketUtil.cpp.i

.PHONY : Snake/SocketUtil.i

# target to preprocess a source file
Snake/SocketUtil.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketUtil.cpp.i
.PHONY : Snake/SocketUtil.cpp.i

Snake/SocketUtil.s: Snake/SocketUtil.cpp.s

.PHONY : Snake/SocketUtil.s

# target to generate assembly for a file
Snake/SocketUtil.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/SocketUtil.cpp.s
.PHONY : Snake/SocketUtil.cpp.s

Snake/StringUtils.o: Snake/StringUtils.cpp.o

.PHONY : Snake/StringUtils.o

# target to build an object file
Snake/StringUtils.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/StringUtils.cpp.o
.PHONY : Snake/StringUtils.cpp.o

Snake/StringUtils.i: Snake/StringUtils.cpp.i

.PHONY : Snake/StringUtils.i

# target to preprocess a source file
Snake/StringUtils.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/StringUtils.cpp.i
.PHONY : Snake/StringUtils.cpp.i

Snake/StringUtils.s: Snake/StringUtils.cpp.s

.PHONY : Snake/StringUtils.s

# target to generate assembly for a file
Snake/StringUtils.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/StringUtils.cpp.s
.PHONY : Snake/StringUtils.cpp.s

Snake/TCPSocket.o: Snake/TCPSocket.cpp.o

.PHONY : Snake/TCPSocket.o

# target to build an object file
Snake/TCPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/TCPSocket.cpp.o
.PHONY : Snake/TCPSocket.cpp.o

Snake/TCPSocket.i: Snake/TCPSocket.cpp.i

.PHONY : Snake/TCPSocket.i

# target to preprocess a source file
Snake/TCPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/TCPSocket.cpp.i
.PHONY : Snake/TCPSocket.cpp.i

Snake/TCPSocket.s: Snake/TCPSocket.cpp.s

.PHONY : Snake/TCPSocket.s

# target to generate assembly for a file
Snake/TCPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/TCPSocket.cpp.s
.PHONY : Snake/TCPSocket.cpp.s

Snake/Timing.o: Snake/Timing.cpp.o

.PHONY : Snake/Timing.o

# target to build an object file
Snake/Timing.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Timing.cpp.o
.PHONY : Snake/Timing.cpp.o

Snake/Timing.i: Snake/Timing.cpp.i

.PHONY : Snake/Timing.i

# target to preprocess a source file
Snake/Timing.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Timing.cpp.i
.PHONY : Snake/Timing.cpp.i

Snake/Timing.s: Snake/Timing.cpp.s

.PHONY : Snake/Timing.s

# target to generate assembly for a file
Snake/Timing.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/Timing.cpp.s
.PHONY : Snake/Timing.cpp.s

Snake/UDPSocket.o: Snake/UDPSocket.cpp.o

.PHONY : Snake/UDPSocket.o

# target to build an object file
Snake/UDPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/UDPSocket.cpp.o
.PHONY : Snake/UDPSocket.cpp.o

Snake/UDPSocket.i: Snake/UDPSocket.cpp.i

.PHONY : Snake/UDPSocket.i

# target to preprocess a source file
Snake/UDPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/UDPSocket.cpp.i
.PHONY : Snake/UDPSocket.cpp.i

Snake/UDPSocket.s: Snake/UDPSocket.cpp.s

.PHONY : Snake/UDPSocket.s

# target to generate assembly for a file
Snake/UDPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/UDPSocket.cpp.s
.PHONY : Snake/UDPSocket.cpp.s

Snake/UtilMath.o: Snake/UtilMath.cpp.o

.PHONY : Snake/UtilMath.o

# target to build an object file
Snake/UtilMath.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/UtilMath.cpp.o
.PHONY : Snake/UtilMath.cpp.o

Snake/UtilMath.i: Snake/UtilMath.cpp.i

.PHONY : Snake/UtilMath.i

# target to preprocess a source file
Snake/UtilMath.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/UtilMath.cpp.i
.PHONY : Snake/UtilMath.cpp.i

Snake/UtilMath.s: Snake/UtilMath.cpp.s

.PHONY : Snake/UtilMath.s

# target to generate assembly for a file
Snake/UtilMath.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/UtilMath.cpp.s
.PHONY : Snake/UtilMath.cpp.s

Snake/World.o: Snake/World.cpp.o

.PHONY : Snake/World.o

# target to build an object file
Snake/World.cpp.o:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/World.cpp.o
.PHONY : Snake/World.cpp.o

Snake/World.i: Snake/World.cpp.i

.PHONY : Snake/World.i

# target to preprocess a source file
Snake/World.cpp.i:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/World.cpp.i
.PHONY : Snake/World.cpp.i

Snake/World.s: Snake/World.cpp.s

.PHONY : Snake/World.s

# target to generate assembly for a file
Snake/World.cpp.s:
	$(MAKE) -f CMakeFiles/Snake.dir/build.make CMakeFiles/Snake.dir/Snake/World.cpp.s
.PHONY : Snake/World.cpp.s

SnakeClient/Client.o: SnakeClient/Client.cpp.o

.PHONY : SnakeClient/Client.o

# target to build an object file
SnakeClient/Client.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/Client.cpp.o
.PHONY : SnakeClient/Client.cpp.o

SnakeClient/Client.i: SnakeClient/Client.cpp.i

.PHONY : SnakeClient/Client.i

# target to preprocess a source file
SnakeClient/Client.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/Client.cpp.i
.PHONY : SnakeClient/Client.cpp.i

SnakeClient/Client.s: SnakeClient/Client.cpp.s

.PHONY : SnakeClient/Client.s

# target to generate assembly for a file
SnakeClient/Client.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/Client.cpp.s
.PHONY : SnakeClient/Client.cpp.s

SnakeClient/FoodClient.o: SnakeClient/FoodClient.cpp.o

.PHONY : SnakeClient/FoodClient.o

# target to build an object file
SnakeClient/FoodClient.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/FoodClient.cpp.o
.PHONY : SnakeClient/FoodClient.cpp.o

SnakeClient/FoodClient.i: SnakeClient/FoodClient.cpp.i

.PHONY : SnakeClient/FoodClient.i

# target to preprocess a source file
SnakeClient/FoodClient.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/FoodClient.cpp.i
.PHONY : SnakeClient/FoodClient.cpp.i

SnakeClient/FoodClient.s: SnakeClient/FoodClient.cpp.s

.PHONY : SnakeClient/FoodClient.s

# target to generate assembly for a file
SnakeClient/FoodClient.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/FoodClient.cpp.s
.PHONY : SnakeClient/FoodClient.cpp.s

SnakeClient/InputManager.o: SnakeClient/InputManager.cpp.o

.PHONY : SnakeClient/InputManager.o

# target to build an object file
SnakeClient/InputManager.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/InputManager.cpp.o
.PHONY : SnakeClient/InputManager.cpp.o

SnakeClient/InputManager.i: SnakeClient/InputManager.cpp.i

.PHONY : SnakeClient/InputManager.i

# target to preprocess a source file
SnakeClient/InputManager.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/InputManager.cpp.i
.PHONY : SnakeClient/InputManager.cpp.i

SnakeClient/InputManager.s: SnakeClient/InputManager.cpp.s

.PHONY : SnakeClient/InputManager.s

# target to generate assembly for a file
SnakeClient/InputManager.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/InputManager.cpp.s
.PHONY : SnakeClient/InputManager.cpp.s

SnakeClient/NetworkManagerClient.o: SnakeClient/NetworkManagerClient.cpp.o

.PHONY : SnakeClient/NetworkManagerClient.o

# target to build an object file
SnakeClient/NetworkManagerClient.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/NetworkManagerClient.cpp.o
.PHONY : SnakeClient/NetworkManagerClient.cpp.o

SnakeClient/NetworkManagerClient.i: SnakeClient/NetworkManagerClient.cpp.i

.PHONY : SnakeClient/NetworkManagerClient.i

# target to preprocess a source file
SnakeClient/NetworkManagerClient.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/NetworkManagerClient.cpp.i
.PHONY : SnakeClient/NetworkManagerClient.cpp.i

SnakeClient/NetworkManagerClient.s: SnakeClient/NetworkManagerClient.cpp.s

.PHONY : SnakeClient/NetworkManagerClient.s

# target to generate assembly for a file
SnakeClient/NetworkManagerClient.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/NetworkManagerClient.cpp.s
.PHONY : SnakeClient/NetworkManagerClient.cpp.s

SnakeClient/RenderManager.o: SnakeClient/RenderManager.cpp.o

.PHONY : SnakeClient/RenderManager.o

# target to build an object file
SnakeClient/RenderManager.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/RenderManager.cpp.o
.PHONY : SnakeClient/RenderManager.cpp.o

SnakeClient/RenderManager.i: SnakeClient/RenderManager.cpp.i

.PHONY : SnakeClient/RenderManager.i

# target to preprocess a source file
SnakeClient/RenderManager.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/RenderManager.cpp.i
.PHONY : SnakeClient/RenderManager.cpp.i

SnakeClient/RenderManager.s: SnakeClient/RenderManager.cpp.s

.PHONY : SnakeClient/RenderManager.s

# target to generate assembly for a file
SnakeClient/RenderManager.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/RenderManager.cpp.s
.PHONY : SnakeClient/RenderManager.cpp.s

SnakeClient/ReplicationManagerClient.o: SnakeClient/ReplicationManagerClient.cpp.o

.PHONY : SnakeClient/ReplicationManagerClient.o

# target to build an object file
SnakeClient/ReplicationManagerClient.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/ReplicationManagerClient.cpp.o
.PHONY : SnakeClient/ReplicationManagerClient.cpp.o

SnakeClient/ReplicationManagerClient.i: SnakeClient/ReplicationManagerClient.cpp.i

.PHONY : SnakeClient/ReplicationManagerClient.i

# target to preprocess a source file
SnakeClient/ReplicationManagerClient.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/ReplicationManagerClient.cpp.i
.PHONY : SnakeClient/ReplicationManagerClient.cpp.i

SnakeClient/ReplicationManagerClient.s: SnakeClient/ReplicationManagerClient.cpp.s

.PHONY : SnakeClient/ReplicationManagerClient.s

# target to generate assembly for a file
SnakeClient/ReplicationManagerClient.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/ReplicationManagerClient.cpp.s
.PHONY : SnakeClient/ReplicationManagerClient.cpp.s

SnakeClient/SnakeClient.o: SnakeClient/SnakeClient.cpp.o

.PHONY : SnakeClient/SnakeClient.o

# target to build an object file
SnakeClient/SnakeClient.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/SnakeClient.cpp.o
.PHONY : SnakeClient/SnakeClient.cpp.o

SnakeClient/SnakeClient.i: SnakeClient/SnakeClient.cpp.i

.PHONY : SnakeClient/SnakeClient.i

# target to preprocess a source file
SnakeClient/SnakeClient.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/SnakeClient.cpp.i
.PHONY : SnakeClient/SnakeClient.cpp.i

SnakeClient/SnakeClient.s: SnakeClient/SnakeClient.cpp.s

.PHONY : SnakeClient/SnakeClient.s

# target to generate assembly for a file
SnakeClient/SnakeClient.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/SnakeClient.cpp.s
.PHONY : SnakeClient/SnakeClient.cpp.s

SnakeClient/main.o: SnakeClient/main.cpp.o

.PHONY : SnakeClient/main.o

# target to build an object file
SnakeClient/main.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/main.cpp.o
.PHONY : SnakeClient/main.cpp.o

SnakeClient/main.i: SnakeClient/main.cpp.i

.PHONY : SnakeClient/main.i

# target to preprocess a source file
SnakeClient/main.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/main.cpp.i
.PHONY : SnakeClient/main.cpp.i

SnakeClient/main.s: SnakeClient/main.cpp.s

.PHONY : SnakeClient/main.s

# target to generate assembly for a file
SnakeClient/main.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeClient.dir/build.make CMakeFiles/SnakeClient.dir/SnakeClient/main.cpp.s
.PHONY : SnakeClient/main.cpp.s

SnakeServer/ClientProxy.o: SnakeServer/ClientProxy.cpp.o

.PHONY : SnakeServer/ClientProxy.o

# target to build an object file
SnakeServer/ClientProxy.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/ClientProxy.cpp.o
.PHONY : SnakeServer/ClientProxy.cpp.o

SnakeServer/ClientProxy.i: SnakeServer/ClientProxy.cpp.i

.PHONY : SnakeServer/ClientProxy.i

# target to preprocess a source file
SnakeServer/ClientProxy.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/ClientProxy.cpp.i
.PHONY : SnakeServer/ClientProxy.cpp.i

SnakeServer/ClientProxy.s: SnakeServer/ClientProxy.cpp.s

.PHONY : SnakeServer/ClientProxy.s

# target to generate assembly for a file
SnakeServer/ClientProxy.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/ClientProxy.cpp.s
.PHONY : SnakeServer/ClientProxy.cpp.s

SnakeServer/DebugPrint.o: SnakeServer/DebugPrint.cpp.o

.PHONY : SnakeServer/DebugPrint.o

# target to build an object file
SnakeServer/DebugPrint.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/DebugPrint.cpp.o
.PHONY : SnakeServer/DebugPrint.cpp.o

SnakeServer/DebugPrint.i: SnakeServer/DebugPrint.cpp.i

.PHONY : SnakeServer/DebugPrint.i

# target to preprocess a source file
SnakeServer/DebugPrint.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/DebugPrint.cpp.i
.PHONY : SnakeServer/DebugPrint.cpp.i

SnakeServer/DebugPrint.s: SnakeServer/DebugPrint.cpp.s

.PHONY : SnakeServer/DebugPrint.s

# target to generate assembly for a file
SnakeServer/DebugPrint.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/DebugPrint.cpp.s
.PHONY : SnakeServer/DebugPrint.cpp.s

SnakeServer/FoodManager.o: SnakeServer/FoodManager.cpp.o

.PHONY : SnakeServer/FoodManager.o

# target to build an object file
SnakeServer/FoodManager.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/FoodManager.cpp.o
.PHONY : SnakeServer/FoodManager.cpp.o

SnakeServer/FoodManager.i: SnakeServer/FoodManager.cpp.i

.PHONY : SnakeServer/FoodManager.i

# target to preprocess a source file
SnakeServer/FoodManager.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/FoodManager.cpp.i
.PHONY : SnakeServer/FoodManager.cpp.i

SnakeServer/FoodManager.s: SnakeServer/FoodManager.cpp.s

.PHONY : SnakeServer/FoodManager.s

# target to generate assembly for a file
SnakeServer/FoodManager.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/FoodManager.cpp.s
.PHONY : SnakeServer/FoodManager.cpp.s

SnakeServer/FoodServer.o: SnakeServer/FoodServer.cpp.o

.PHONY : SnakeServer/FoodServer.o

# target to build an object file
SnakeServer/FoodServer.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/FoodServer.cpp.o
.PHONY : SnakeServer/FoodServer.cpp.o

SnakeServer/FoodServer.i: SnakeServer/FoodServer.cpp.i

.PHONY : SnakeServer/FoodServer.i

# target to preprocess a source file
SnakeServer/FoodServer.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/FoodServer.cpp.i
.PHONY : SnakeServer/FoodServer.cpp.i

SnakeServer/FoodServer.s: SnakeServer/FoodServer.cpp.s

.PHONY : SnakeServer/FoodServer.s

# target to generate assembly for a file
SnakeServer/FoodServer.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/FoodServer.cpp.s
.PHONY : SnakeServer/FoodServer.cpp.s

SnakeServer/NetworkManagerServer.o: SnakeServer/NetworkManagerServer.cpp.o

.PHONY : SnakeServer/NetworkManagerServer.o

# target to build an object file
SnakeServer/NetworkManagerServer.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/NetworkManagerServer.cpp.o
.PHONY : SnakeServer/NetworkManagerServer.cpp.o

SnakeServer/NetworkManagerServer.i: SnakeServer/NetworkManagerServer.cpp.i

.PHONY : SnakeServer/NetworkManagerServer.i

# target to preprocess a source file
SnakeServer/NetworkManagerServer.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/NetworkManagerServer.cpp.i
.PHONY : SnakeServer/NetworkManagerServer.cpp.i

SnakeServer/NetworkManagerServer.s: SnakeServer/NetworkManagerServer.cpp.s

.PHONY : SnakeServer/NetworkManagerServer.s

# target to generate assembly for a file
SnakeServer/NetworkManagerServer.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/NetworkManagerServer.cpp.s
.PHONY : SnakeServer/NetworkManagerServer.cpp.s

SnakeServer/ReplicationManagerServer.o: SnakeServer/ReplicationManagerServer.cpp.o

.PHONY : SnakeServer/ReplicationManagerServer.o

# target to build an object file
SnakeServer/ReplicationManagerServer.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/ReplicationManagerServer.cpp.o
.PHONY : SnakeServer/ReplicationManagerServer.cpp.o

SnakeServer/ReplicationManagerServer.i: SnakeServer/ReplicationManagerServer.cpp.i

.PHONY : SnakeServer/ReplicationManagerServer.i

# target to preprocess a source file
SnakeServer/ReplicationManagerServer.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/ReplicationManagerServer.cpp.i
.PHONY : SnakeServer/ReplicationManagerServer.cpp.i

SnakeServer/ReplicationManagerServer.s: SnakeServer/ReplicationManagerServer.cpp.s

.PHONY : SnakeServer/ReplicationManagerServer.s

# target to generate assembly for a file
SnakeServer/ReplicationManagerServer.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/ReplicationManagerServer.cpp.s
.PHONY : SnakeServer/ReplicationManagerServer.cpp.s

SnakeServer/Server.o: SnakeServer/Server.cpp.o

.PHONY : SnakeServer/Server.o

# target to build an object file
SnakeServer/Server.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/Server.cpp.o
.PHONY : SnakeServer/Server.cpp.o

SnakeServer/Server.i: SnakeServer/Server.cpp.i

.PHONY : SnakeServer/Server.i

# target to preprocess a source file
SnakeServer/Server.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/Server.cpp.i
.PHONY : SnakeServer/Server.cpp.i

SnakeServer/Server.s: SnakeServer/Server.cpp.s

.PHONY : SnakeServer/Server.s

# target to generate assembly for a file
SnakeServer/Server.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/Server.cpp.s
.PHONY : SnakeServer/Server.cpp.s

SnakeServer/SnakeServer.o: SnakeServer/SnakeServer.cpp.o

.PHONY : SnakeServer/SnakeServer.o

# target to build an object file
SnakeServer/SnakeServer.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/SnakeServer.cpp.o
.PHONY : SnakeServer/SnakeServer.cpp.o

SnakeServer/SnakeServer.i: SnakeServer/SnakeServer.cpp.i

.PHONY : SnakeServer/SnakeServer.i

# target to preprocess a source file
SnakeServer/SnakeServer.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/SnakeServer.cpp.i
.PHONY : SnakeServer/SnakeServer.cpp.i

SnakeServer/SnakeServer.s: SnakeServer/SnakeServer.cpp.s

.PHONY : SnakeServer/SnakeServer.s

# target to generate assembly for a file
SnakeServer/SnakeServer.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/SnakeServer.cpp.s
.PHONY : SnakeServer/SnakeServer.cpp.s

SnakeServer/main.o: SnakeServer/main.cpp.o

.PHONY : SnakeServer/main.o

# target to build an object file
SnakeServer/main.cpp.o:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/main.cpp.o
.PHONY : SnakeServer/main.cpp.o

SnakeServer/main.i: SnakeServer/main.cpp.i

.PHONY : SnakeServer/main.i

# target to preprocess a source file
SnakeServer/main.cpp.i:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/main.cpp.i
.PHONY : SnakeServer/main.cpp.i

SnakeServer/main.s: SnakeServer/main.cpp.s

.PHONY : SnakeServer/main.s

# target to generate assembly for a file
SnakeServer/main.cpp.s:
	$(MAKE) -f CMakeFiles/SnakeServer.dir/build.make CMakeFiles/SnakeServer.dir/SnakeServer/main.cpp.s
.PHONY : SnakeServer/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Snake"
	@echo "... rebuild_cache"
	@echo "... SnakeServer"
	@echo "... SnakeClient"
	@echo "... edit_cache"
	@echo "... Snake/Console.o"
	@echo "... Snake/Console.i"
	@echo "... Snake/Console.s"
	@echo "... Snake/ConsoleBuffer.o"
	@echo "... Snake/ConsoleBuffer.i"
	@echo "... Snake/ConsoleBuffer.s"
	@echo "... Snake/Context.o"
	@echo "... Snake/Context.i"
	@echo "... Snake/Context.s"
	@echo "... Snake/Food.o"
	@echo "... Snake/Food.i"
	@echo "... Snake/Food.s"
	@echo "... Snake/GameObject.o"
	@echo "... Snake/GameObject.i"
	@echo "... Snake/GameObject.s"
	@echo "... Snake/GameObjectRegistry.o"
	@echo "... Snake/GameObjectRegistry.i"
	@echo "... Snake/GameObjectRegistry.s"
	@echo "... Snake/InputState.o"
	@echo "... Snake/InputState.i"
	@echo "... Snake/InputState.s"
	@echo "... Snake/MemoryBitStream.o"
	@echo "... Snake/MemoryBitStream.i"
	@echo "... Snake/MemoryBitStream.s"
	@echo "... Snake/Move.o"
	@echo "... Snake/Move.i"
	@echo "... Snake/Move.s"
	@echo "... Snake/MoveList.o"
	@echo "... Snake/MoveList.i"
	@echo "... Snake/MoveList.s"
	@echo "... Snake/NetworkManager.o"
	@echo "... Snake/NetworkManager.i"
	@echo "... Snake/NetworkManager.s"
	@echo "... Snake/ObjectManager.o"
	@echo "... Snake/ObjectManager.i"
	@echo "... Snake/ObjectManager.s"
	@echo "... Snake/ScoreBoardManager.o"
	@echo "... Snake/ScoreBoardManager.i"
	@echo "... Snake/ScoreBoardManager.s"
	@echo "... Snake/Snake.o"
	@echo "... Snake/Snake.i"
	@echo "... Snake/Snake.s"
	@echo "... Snake/SocketAddress.o"
	@echo "... Snake/SocketAddress.i"
	@echo "... Snake/SocketAddress.s"
	@echo "... Snake/SocketAddressFactory.o"
	@echo "... Snake/SocketAddressFactory.i"
	@echo "... Snake/SocketAddressFactory.s"
	@echo "... Snake/SocketUtil.o"
	@echo "... Snake/SocketUtil.i"
	@echo "... Snake/SocketUtil.s"
	@echo "... Snake/StringUtils.o"
	@echo "... Snake/StringUtils.i"
	@echo "... Snake/StringUtils.s"
	@echo "... Snake/TCPSocket.o"
	@echo "... Snake/TCPSocket.i"
	@echo "... Snake/TCPSocket.s"
	@echo "... Snake/Timing.o"
	@echo "... Snake/Timing.i"
	@echo "... Snake/Timing.s"
	@echo "... Snake/UDPSocket.o"
	@echo "... Snake/UDPSocket.i"
	@echo "... Snake/UDPSocket.s"
	@echo "... Snake/UtilMath.o"
	@echo "... Snake/UtilMath.i"
	@echo "... Snake/UtilMath.s"
	@echo "... Snake/World.o"
	@echo "... Snake/World.i"
	@echo "... Snake/World.s"
	@echo "... SnakeClient/Client.o"
	@echo "... SnakeClient/Client.i"
	@echo "... SnakeClient/Client.s"
	@echo "... SnakeClient/FoodClient.o"
	@echo "... SnakeClient/FoodClient.i"
	@echo "... SnakeClient/FoodClient.s"
	@echo "... SnakeClient/InputManager.o"
	@echo "... SnakeClient/InputManager.i"
	@echo "... SnakeClient/InputManager.s"
	@echo "... SnakeClient/NetworkManagerClient.o"
	@echo "... SnakeClient/NetworkManagerClient.i"
	@echo "... SnakeClient/NetworkManagerClient.s"
	@echo "... SnakeClient/RenderManager.o"
	@echo "... SnakeClient/RenderManager.i"
	@echo "... SnakeClient/RenderManager.s"
	@echo "... SnakeClient/ReplicationManagerClient.o"
	@echo "... SnakeClient/ReplicationManagerClient.i"
	@echo "... SnakeClient/ReplicationManagerClient.s"
	@echo "... SnakeClient/SnakeClient.o"
	@echo "... SnakeClient/SnakeClient.i"
	@echo "... SnakeClient/SnakeClient.s"
	@echo "... SnakeClient/main.o"
	@echo "... SnakeClient/main.i"
	@echo "... SnakeClient/main.s"
	@echo "... SnakeServer/ClientProxy.o"
	@echo "... SnakeServer/ClientProxy.i"
	@echo "... SnakeServer/ClientProxy.s"
	@echo "... SnakeServer/DebugPrint.o"
	@echo "... SnakeServer/DebugPrint.i"
	@echo "... SnakeServer/DebugPrint.s"
	@echo "... SnakeServer/FoodManager.o"
	@echo "... SnakeServer/FoodManager.i"
	@echo "... SnakeServer/FoodManager.s"
	@echo "... SnakeServer/FoodServer.o"
	@echo "... SnakeServer/FoodServer.i"
	@echo "... SnakeServer/FoodServer.s"
	@echo "... SnakeServer/NetworkManagerServer.o"
	@echo "... SnakeServer/NetworkManagerServer.i"
	@echo "... SnakeServer/NetworkManagerServer.s"
	@echo "... SnakeServer/ReplicationManagerServer.o"
	@echo "... SnakeServer/ReplicationManagerServer.i"
	@echo "... SnakeServer/ReplicationManagerServer.s"
	@echo "... SnakeServer/Server.o"
	@echo "... SnakeServer/Server.i"
	@echo "... SnakeServer/Server.s"
	@echo "... SnakeServer/SnakeServer.o"
	@echo "... SnakeServer/SnakeServer.i"
	@echo "... SnakeServer/SnakeServer.s"
	@echo "... SnakeServer/main.o"
	@echo "... SnakeServer/main.i"
	@echo "... SnakeServer/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

